apiVersion: v1
kind: Pod
metadata:
  name: busybox-kata-clone
  annotations:
    io.katacontainers.restore-from: "bbdemo"
spec:
  runtimeClassName: kata
  nodeSelector:
    kubernetes.io/hostname: aks-nodepool1-23826427-vmss000000
  containers:
    - name: busybox
      image: docker.io/library/busybox:latest
      imagePullPolicy: IfNotPresent
      command: ["sleep", "infinity"]
